# app/services/report.py
"""
Satark — PDF Report Generation Service.
Generates professional, branded incident reports using ReportLab.
"""
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    HRFlowable,
    ListFlowable,
    ListItem,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.incident import Incident

# ── Color mapping (display only — NOT business logic) ───────────────────────
CLASSIFICATION_COLORS = {
    "phishing": colors.HexColor("#F97316"),
    "malware": colors.HexColor("#EF4444"),
    "fraud": colors.HexColor("#8B5CF6"),
    "espionage": colors.HexColor("#DC2626"),
    "opsec_risk": colors.HexColor("#EAB308"),
    "safe": colors.HexColor("#22C55E"),
}

PRIORITY_COLORS = {
    "critical": colors.HexColor("#EF4444"),
    "high": colors.HexColor("#F97316"),
    "medium": colors.HexColor("#EAB308"),
    "low": colors.HexColor("#22C55E"),
}

NAVY = colors.HexColor("#0F172A")
BLUE = colors.HexColor("#3B82F6")
LIGHT_GRAY = colors.HexColor("#F8FAFC")
BORDER_GRAY = colors.HexColor("#E2E8F0")


def _build_styles() -> dict:
    """Build custom paragraph styles for the Satark report."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "SatarkTitle",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=22,
            textColor=NAVY,
            spaceAfter=4 * mm,
            alignment=TA_CENTER,
        ),
        "subtitle": ParagraphStyle(
            "SatarkSubtitle",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=11,
            textColor=colors.HexColor("#64748B"),
            alignment=TA_CENTER,
            spaceAfter=6 * mm,
        ),
        "section_heading": ParagraphStyle(
            "SectionHeading",
            parent=base["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            textColor=NAVY,
            spaceBefore=8 * mm,
            spaceAfter=3 * mm,
        ),
        "body": ParagraphStyle(
            "SatarkBody",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#334155"),
        ),
        "body_bold": ParagraphStyle(
            "SatarkBodyBold",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#1E293B"),
        ),
        "small": ParagraphStyle(
            "SatarkSmall",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            textColor=colors.HexColor("#94A3B8"),
        ),
        "mono": ParagraphStyle(
            "SatarkMono",
            parent=base["Normal"],
            fontName="Courier",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#334155"),
        ),
    }


def _add_footer(canvas, doc):
    """Draw footer on every page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#94A3B8"))
    footer_text = (
        f"Generated by Satark AI Intelligence Platform | "
        f"SIH 2025 PS 25210 | {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    canvas.drawCentredString(A4[0] / 2, 15 * mm, footer_text)
    canvas.drawRightString(
        A4[0] - 20 * mm, 15 * mm, f"Page {doc.page}"
    )
    canvas.restoreState()


def _build_header(incident: Incident, styles: dict) -> list:
    """Build the report header with case number and date."""
    elements = []
    elements.append(Paragraph("SATARK", styles["title"]))
    elements.append(
        Paragraph(
            "AI-Powered Cyber Incident Intelligence",
            styles["subtitle"],
        )
    )
    elements.append(
        HRFlowable(
            width="100%",
            thickness=1,
            color=BORDER_GRAY,
            spaceAfter=4 * mm,
        )
    )

    # Case info table
    created = incident.created_at.strftime("%d %b %Y, %H:%M UTC")
    info_data = [
        [
            Paragraph(f"<b>Case Number:</b> {incident.case_number}", styles["body"]),
            Paragraph(f"<b>Date:</b> {created}", styles["body"]),
        ],
        [
            Paragraph(
                f"<b>Input Type:</b> {incident.input_type.upper()}",
                styles["body"],
            ),
            Paragraph(
                f"<b>Status:</b> {(incident.status or 'unknown').upper()}",
                styles["body"],
            ),
        ],
    ]
    info_table = Table(info_data, colWidths=["50%", "50%"])
    info_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2 * mm),
            ]
        )
    )
    elements.append(info_table)
    elements.append(Spacer(1, 4 * mm))
    return elements


def _build_classification_badge(incident: Incident, styles: dict) -> list:
    """Build the classification badge and threat score bar."""
    elements = []
    classification = incident.classification or "pending"
    badge_color = CLASSIFICATION_COLORS.get(classification, colors.gray)
    priority = incident.priority or "—"
    priority_color = PRIORITY_COLORS.get(priority, colors.gray)

    badge_data = [
        [
            Paragraph(
                f"<font color='white'><b>{classification.upper()}</b></font>",
                ParagraphStyle(
                    "Badge",
                    fontName="Helvetica-Bold",
                    fontSize=11,
                    alignment=TA_CENTER,
                    textColor=colors.white,
                ),
            ),
            Paragraph(
                f"<b>Threat Score:</b> {incident.threat_score or '—'}/100",
                styles["body"],
            ),
            Paragraph(
                f"<b>Priority:</b> {priority.upper()}",
                styles["body"],
            ),
            Paragraph(
                f"<b>Confidence:</b> {f'{incident.confidence:.0%}' if incident.confidence else '—'}",
                styles["body"],
            ),
        ]
    ]
    badge_table = Table(badge_data, colWidths=["25%", "25%", "25%", "25%"])
    badge_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, 0), badge_color),
                ("TEXTCOLOR", (0, 0), (0, 0), colors.white),
                ("ALIGN", (0, 0), (0, 0), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ROUNDEDCORNERS", [4, 0, 0, 4]),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3 * mm),
                ("TOPPADDING", (0, 0), (-1, -1), 3 * mm),
                ("LEFTPADDING", (0, 0), (-1, -1), 3 * mm),
                ("BACKGROUND", (1, 0), (-1, -1), LIGHT_GRAY),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
            ]
        )
    )
    elements.append(badge_table)
    elements.append(Spacer(1, 4 * mm))
    return elements


def _build_incident_summary(incident: Incident, styles: dict) -> list:
    """Build the incident summary section."""
    elements = []
    elements.append(Paragraph("Incident Summary", styles["section_heading"]))

    if incident.description:
        elements.append(
            Paragraph(f"<b>Description:</b> {incident.description}", styles["body"])
        )
        elements.append(Spacer(1, 2 * mm))

    if incident.input_content:
        content = incident.input_content[:500]
        if len(incident.input_content) > 500:
            content += "..."
        elements.append(Paragraph("<b>Submitted Content:</b>", styles["body"]))
        elements.append(Spacer(1, 1 * mm))

        content_data = [[Paragraph(content, styles["mono"])]]
        content_table = Table(content_data, colWidths=["100%"])
        content_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
                    ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                    ("LEFTPADDING", (0, 0), (-1, -1), 3 * mm),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 3 * mm),
                    ("TOPPADDING", (0, 0), (-1, -1), 2 * mm),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 2 * mm),
                ]
            )
        )
        elements.append(content_table)

    return elements


def _build_ai_analysis(incident: Incident, styles: dict) -> list:
    """Build AI analysis findings, IOC table, risk factors, mitigation playbook."""
    elements = []
    ai = incident.ai_analysis

    if not ai:
        elements.append(Paragraph("AI Analysis", styles["section_heading"]))
        elements.append(
            Paragraph(
                "<i>Analysis pending — report generated before AI processing completed.</i>",
                styles["body"],
            )
        )
        return elements

    # Summary
    elements.append(Paragraph("AI Analysis Summary", styles["section_heading"]))
    summary_data = [[Paragraph(ai.get("summary", "No summary available."), styles["body"])]]
    summary_table = Table(summary_data, colWidths=["100%"])
    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("LEFTPADDING", (0, 0), (-1, -1), 4 * mm),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4 * mm),
                ("TOPPADDING", (0, 0), (-1, -1), 3 * mm),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3 * mm),
            ]
        )
    )
    elements.append(summary_table)

    # IOC Table
    indicators = ai.get("indicators", [])
    if indicators:
        elements.append(
            Paragraph("Indicators of Compromise (IOCs)", styles["section_heading"])
        )
        ioc_data = [
            [
                Paragraph("<b>#</b>", styles["body_bold"]),
                Paragraph("<b>Indicator</b>", styles["body_bold"]),
            ]
        ]
        for idx, ioc in enumerate(indicators, 1):
            ioc_data.append(
                [
                    Paragraph(str(idx), styles["body"]),
                    Paragraph(ioc, styles["mono"]),
                ]
            )
        ioc_table = Table(ioc_data, colWidths=["10%", "90%"])
        ioc_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
                    ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                    ("INNERGRID", (0, 0), (-1, -1), 0.25, BORDER_GRAY),
                    ("LEFTPADDING", (0, 0), (-1, -1), 2 * mm),
                    ("TOPPADDING", (0, 0), (-1, -1), 1.5 * mm),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5 * mm),
                ]
            )
        )
        elements.append(ioc_table)

    # Risk Factors
    risk_factors = ai.get("risk_factors", [])
    if risk_factors:
        elements.append(Paragraph("Risk Factors", styles["section_heading"]))
        items = [ListItem(Paragraph(rf, styles["body"])) for rf in risk_factors]
        elements.append(
            ListFlowable(items, bulletType="bullet", bulletFontSize=8, leftIndent=10)
        )

    # Mitigation Playbook
    mitigation = ai.get("mitigation_steps", [])
    if mitigation:
        elements.append(Paragraph("Mitigation Playbook", styles["section_heading"]))
        items = [ListItem(Paragraph(step, styles["body"])) for step in mitigation]
        elements.append(
            ListFlowable(items, bulletType="1", bulletFontSize=10, leftIndent=10)
        )

    return elements


def _build_evidence_log(incident: Incident, styles: dict) -> list:
    """Build the evidence files log."""
    files = incident.evidence_files
    if not files:
        return []

    elements = []
    elements.append(Paragraph("Evidence Log", styles["section_heading"]))

    ev_data = [
        [
            Paragraph("<b>Filename</b>", styles["body_bold"]),
            Paragraph("<b>MIME Type</b>", styles["body_bold"]),
            Paragraph("<b>Size</b>", styles["body_bold"]),
            Paragraph("<b>SHA-256</b>", styles["body_bold"]),
        ]
    ]
    for ef in files:
        size_kb = f"{ef.file_size / 1024:.1f} KB"
        checksum_short = ef.checksum[:16] + "..." if len(ef.checksum) > 16 else ef.checksum
        ev_data.append(
            [
                Paragraph(ef.original_filename, styles["body"]),
                Paragraph(ef.mime_type, styles["mono"]),
                Paragraph(size_kb, styles["body"]),
                Paragraph(checksum_short, styles["mono"]),
            ]
        )

    ev_table = Table(ev_data, colWidths=["30%", "25%", "15%", "30%"])
    ev_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, BORDER_GRAY),
                ("LEFTPADDING", (0, 0), (-1, -1), 2 * mm),
                ("TOPPADDING", (0, 0), (-1, -1), 1.5 * mm),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5 * mm),
            ]
        )
    )
    elements.append(ev_table)
    return elements


def _build_audit_trail(incident: Incident, styles: dict) -> list:
    """Build the audit trail timeline."""
    logs = incident.audit_logs
    if not logs:
        return []

    elements = []
    elements.append(Paragraph("Audit Trail", styles["section_heading"]))

    audit_data = [
        [
            Paragraph("<b>Timestamp</b>", styles["body_bold"]),
            Paragraph("<b>Actor</b>", styles["body_bold"]),
            Paragraph("<b>Action</b>", styles["body_bold"]),
            Paragraph("<b>Details</b>", styles["body_bold"]),
        ]
    ]
    sorted_logs = sorted(logs, key=lambda x: x.created_at)
    for log in sorted_logs:
        ts = log.created_at.strftime("%d %b %Y %H:%M")
        details_str = ""
        if log.details:
            details_str = ", ".join(
                f"{k}: {v}" for k, v in log.details.items()
            )
            if len(details_str) > 60:
                details_str = details_str[:57] + "..."
        audit_data.append(
            [
                Paragraph(ts, styles["small"]),
                Paragraph(log.actor_label, styles["body"]),
                Paragraph(log.action.replace("_", " ").title(), styles["body"]),
                Paragraph(details_str, styles["small"]),
            ]
        )

    audit_table = Table(audit_data, colWidths=["22%", "18%", "25%", "35%"])
    audit_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_GRAY]),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ("INNERGRID", (0, 0), (-1, -1), 0.25, BORDER_GRAY),
                ("LEFTPADDING", (0, 0), (-1, -1), 2 * mm),
                ("TOPPADDING", (0, 0), (-1, -1), 1.5 * mm),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5 * mm),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    elements.append(audit_table)
    return elements


def generate_report(incident: Incident) -> bytes:
    """
    Generate a PDF report for an incident.

    Args:
        incident: Incident with eager-loaded evidence_files and audit_logs.

    Returns:
        PDF file content as bytes.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=20 * mm,
        bottomMargin=25 * mm,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        title=f"Satark Report — {incident.case_number}",
        author="Satark AI Intelligence Platform",
    )

    styles = _build_styles()
    elements = []

    # 1. Header
    elements.extend(_build_header(incident, styles))

    # 2. Classification badge + threat score + priority
    elements.extend(_build_classification_badge(incident, styles))

    # 3. Incident summary
    elements.extend(_build_incident_summary(incident, styles))

    # 4-7. AI analysis (summary, IOCs, risk factors, mitigation)
    elements.extend(_build_ai_analysis(incident, styles))

    # 8. Evidence log
    elements.extend(_build_evidence_log(incident, styles))

    # 9. Audit trail
    elements.extend(_build_audit_trail(incident, styles))

    doc.build(elements, onFirstPage=_add_footer, onLaterPages=_add_footer)
    return buffer.getvalue()
